# Generated by Django 4.2 on 2026-03-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('center_id', models.IntegerField(blank=True, null=True)),
                ('meal_id', models.IntegerField()),
                ('checkout_price', models.FloatField()),
                ('base_price', models.FloatField()),
                ('emailer_for_promotion', models.IntegerField()),
                ('homepage_featured', models.IntegerField()),
                ('city_code', models.IntegerField()),
                ('region_code', models.IntegerField()),
                ('op_area', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('cuisine', models.CharField(max_length=100)),
                ('center_type', models.CharField(blank=True, max_length=50, null=True)),
                ('orders', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('predicted_orders', models.IntegerField()),
                ('model_used', models.CharField(max_length=50)),
            ],
        ),
    ]
